services:
  mysql:
    image: mysql:8.0
    container_name: sbs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  test-api:
    image: eclipse-temurin:21-jdk
    container_name: sbs-java-api
    ports:
      - "8085:8085"
    volumes:
      - ./app.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass

volumes:
  mysql-data: