services:
  mysql:
    image: mysql:8.0
    container_name: sbs-mysql-fresh-latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3308:3306"
    volumes:
      - mysql-data-fresh:/var/lib/mysql

  test-api:   # ✅ NOW INSIDE services
    image: otsi/sbs-java-api-new-fresh-latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sbs-java-api-fresh-latest
    ports:
      - "8087:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass

volumes:
  mysql-data-fresh-latest:
