spring.application.name=docker-support

# ============================================================
# DATASOURCE (Local environment)
# ============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/docker
spring.datasource.username=root
spring.datasource.password=fNo#1262
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver